/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package SumColumn;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {

    @Test
    public void tests() {
        int[][] a = {
            {-5, -2, -3, 7},
            {1, -5, -2, 2},
            {1, -2, 3, -4}
        };
        assertEquals(-2, App.sumColumn(a, 2));
        int[][] b = {
            {1, 2, 3, 4, 4, 7, 1, 6, 3, 7, 10},
            {7, 2, 3, 4, 5, 2, -3, -6, 4, 7, 11}
        };
        assertEquals(0, App.sumColumn(b, 7));
        int[][] c = {
            {-1, -2},
            {-3, -4}
        };
        assertEquals(-4, App.sumColumn(c, 0));
    }
}
